<?php

return [
    'name' => 'Allen Christopher Aduan',
    'display_name' => 'Allen Christopher',
    'title' => 'Software Engineer & Laravel Developer | Dubai',
    'description' => 'Portfolio of Allen Christopher Aduan, a software engineer from the Philippines based in Dubai. Expert in Laravel applications, APIs, and digital products.',
    'email' => 'business.allen.dev@gmail.com',
    'location' => [
        'city' => 'Dubai',
        'country' => 'United Arab Emirates',
        'country_code' => 'AE',
    ],
    'phones' => [
        'uae' => '+971526655217',
        'ph' => '+639163155018',
    ],
    'profiles' => [
        'github' => 'https://github.com/allenaduan0',
        'linkedin' => 'https://www.linkedin.com/in/allen-christopher-aduan-401bb61b6/',
    ],
    'expertise' => [
        'Software Engineering',
        'Web Developer',
        'Software Developer',
        'Backend Engineer',
        'Backend Developer',
        'FullStack Developer',
        'FullStack Engineer',
        'FrontEnd Engineer',
        'FrontEnd Developer',
        'Laravel',
        'CodeIgniter',
        'PHP',
        'RESTful API Design',
        'PostgreSQL',
        'MongoDB',
        'Payment Systems',
        'Double-entry Ledgers',
        'React.js',
        'Next.js',
        'Node.js',
        'JavaScript',
        'Tailwind CSS',
        'Product Engineering',
        'Express.js',
        'MySQL',
        'Bootstrap',
        'HTML5/CSS3',
        'Flutter',
        'Postman',
        'Git',
        'DevOps',
        'Docker',
        'Linux',
        'Continuous Integration / Continuous Deployment',
        'CI/CD',
    ],
];